unstable_features = true
edition = "2018"
style_edition = "2018"
max_width = 80
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
condense_wildcard_suffixes = true
hex_literal_case = "Upper"
normalize_comments = true
normalize_doc_attributes = true
format_code_in_doc_comments = true
# float_literal_trailing_zero = "Always" # unreleased
